### ISSUE TITLE
Add Merge Sort algorithm similar to bubble sort 

### ISSUE THREAD

**Issue by pccoe-acm** [pccoe-acm-hacktoberfest-2023/Sorting_Visualizer#1]

**Comment by Kinjal2004** [comment]
I want to work on this issue

**Comment by Girish345** [comment]
I want to work on that can you please assign it to me

**Comment by PrathameshTheurkar** [comment]
Guys there is no need of assigning the issue , its on the first come first serve basis , feel free to raise a PR  and Good Luck !
